# theme = "catppuccin_mocha"
# theme = "custom"
theme = "base16_transparent"

[editor]
line-number = "relative"
mouse = true
bufferline = "multiple"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "block"


